### ISSUE TITLE
License

### ISSUE THREAD

**Issue by driskull** [2gis/mock-geolocation#3]
Can you add a license to this repo? :)

**Comment by Trufi** [comment]
Done https://github.com/2gis/mock-geolocation/blob/master/LICENSE.md

**Comment by driskull** [comment]
thanks!

**Comment by tartakynov** [comment]
test

________________________________
This message is confidential and is for the sole use of the intended recipient(s). It may also be privileged or otherwise protected by copyright or other legal rules. If you have received it by mistake please let us know by reply email and delete it from your system. It is prohibited to copy this message or disclose its content to anyone. Any confidentiality or privilege is not waived or lost by any mistaken delivery or unauthorized disclosure of the message. All messages sent to and from Agoda may be monitored to ensure compliance with company policies, to protect the company's interests and to remove potential malware. Electronic messages may be intercepted, amended, lost or deleted, or contain viruses.
